/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgrado.postgradosistema.cliente.ingresante;

import com.postgrado.postgradosistema.logic.*;
import com.postgrado.postgradosistema.modelo.*;

import javax.swing.*;
import java.sql.SQLException;
import java.util.List;

/**
 * @author ESTUDIANTE-WALTHER GALAN VITE
 */
public class FrmRegistrarIngresante extends javax.swing.JDialog {
    CicloLogic cicloLogic = new CicloLogic();
    SedeLogic sedeLogic = new SedeLogic();
    EspecialidadLogic especialidadLogic = new EspecialidadLogic();
    ProyectoLogic proyectoLogic = new ProyectoLogic();

    int xMouse, yMouse;

    /**
     * Creates new form FrmRegistrarIngresante
     */
    public FrmRegistrarIngresante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/enfermeria.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtNombreIngresante = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtCodigoIngresante = new javax.swing.JTextField();
        jtxtDniIngresante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcomboboxCiclo = new javax.swing.JComboBox<>();
        jtxtBuscarCiclo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtBuscarSede = new javax.swing.JTextField();
        jcomboboxSede = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxtBuscarEspecialidad = new javax.swing.JTextField();
        jcomboboxEspecialidad = new javax.swing.JComboBox<>();
        PROYECTO = new javax.swing.JLabel();
        jtxtBuscarProyectoPorId = new javax.swing.JTextField();
        jcomboboxProyecto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jbtnRegistrarIngresante = new javax.swing.JButton();
        jbtnSalirRegistrarIngresante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 50));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRAR ESTUDIANTE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 287, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel3.setText("DNI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel4.setText("NOMBRE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 222, -1, -1));
        jPanel2.add(jtxtNombreIngresante, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 213, 270, 40));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel5.setText("CODIGO");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 288, -1, -1));
        jPanel2.add(jtxtCodigoIngresante, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 283, 270, 43));
        jPanel2.add(jtxtDniIngresante, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 149, 270, 40));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel6.setText("CICLO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jPanel2.add(jcomboboxCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 140, 320, 40));

        jtxtBuscarCiclo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarCicloKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarCiclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 198, 40));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel7.setText("SEDE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jtxtBuscarSede.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarSedeKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 198, 40));

        jPanel2.add(jcomboboxSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 320, 38));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel8.setText("ESPECIALIDAD");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jtxtBuscarEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarEspecialidadKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 198, 43));

        jcomboboxEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboboxEspecialidadActionPerformed(evt);
            }
        });
        jPanel2.add(jcomboboxEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 350, 41));

        PROYECTO.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        PROYECTO.setText("ID PROYECTO");
        jPanel2.add(PROYECTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        jtxtBuscarProyectoPorId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                try {
                    jtxtBuscarProyectoPorIdKeyReleased(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jPanel2.add(jtxtBuscarProyectoPorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 80, 35));

        jPanel2.add(jcomboboxProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 450, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar023.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 39));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1200, 480));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jbtnRegistrarIngresante.setBackground(new java.awt.Color(204, 204, 204));
        jbtnRegistrarIngresante.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnRegistrarIngresante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        jbtnRegistrarIngresante.setText("Registrar");
        jbtnRegistrarIngresante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarIngresanteActionPerformed(evt);
            }
        });

        jbtnSalirRegistrarIngresante.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSalirRegistrarIngresante.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnSalirRegistrarIngresante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jbtnSalirRegistrarIngresante.setText("Salir");
        jbtnSalirRegistrarIngresante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirRegistrarIngresanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(317, 317, 317)
                                .addComponent(jbtnRegistrarIngresante, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180)
                                .addComponent(jbtnSalirRegistrarIngresante, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtnRegistrarIngresante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnSalirRegistrarIngresante, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1200, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirRegistrarIngresanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirRegistrarIngresanteActionPerformed

        this.dispose();
    }//GEN-LAST:event_jbtnSalirRegistrarIngresanteActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jbtnRegistrarIngresanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarIngresanteActionPerformed
        String dni = jtxtDniIngresante.getText();
        String nombre = jtxtNombreIngresante.getText().trim();
        String codigo = jtxtCodigoIngresante.getText().trim();
        String nombreCiclo = (String) jcomboboxCiclo.getSelectedItem();
        String nombreEspecialidad = (String) jcomboboxEspecialidad.getSelectedItem();
        String nombreSede = (String) jcomboboxSede.getSelectedItem();
        String nombreProyecto = (String) jcomboboxProyecto.getSelectedItem();

        if (!nombre.isEmpty() && !codigo.isEmpty() && !nombreCiclo.isEmpty() && !nombreEspecialidad.isEmpty() && !nombreSede.isEmpty() && !nombreProyecto.isEmpty()) {
            CicloLogic cicloLogic = new CicloLogic();
            List<Ciclo> ciclos = cicloLogic.buscarCicloPorNombre(nombreCiclo);

            EspecialidadLogic especialidadLogic = new EspecialidadLogic();
            List<Especialidad> especialidades = especialidadLogic.buscarEspecialidadPorNombre(nombreEspecialidad);

            SedeLogic sedeLogic = new SedeLogic();
            List<Sede> sedes = sedeLogic.buscarSedePorNombre(nombreSede);

            ProyectoLogic proyectoLogic = new ProyectoLogic();
            List<Proyecto> proyectos = proyectoLogic.buscarProyectoPorNombre(nombreProyecto);

            if (!nombreCiclo.isEmpty() && !nombreEspecialidad.isEmpty() && !nombreSede.isEmpty() && !nombreProyecto.isEmpty()) {
                Ciclo cicloSeleccionado = ciclos.get(0);
                Especialidad especialidadSeleccionada = especialidades.get(0);
                Sede sedeSeleccionada = sedes.get(0);
                Proyecto proyectoSeleccionado = proyectos.get(0);

                Ingresante ingresante = new Ingresante();
                ingresante.setDni(dni);
                ingresante.setNombre(nombre);
                ingresante.setCodigo(codigo);
                ingresante.setCiclo(cicloSeleccionado);
                ingresante.setEspecialidad(especialidadSeleccionada);
                ingresante.setSede(sedeSeleccionada);
                ingresante.setProyecto(proyectoSeleccionado);

                IngresanteLogic ingresanteLogic = new IngresanteLogic();
                if (ingresanteLogic.registrarIngresante(ingresante)) {
                    JOptionPane.showMessageDialog(null, "Ingresante registrado correctamente");
                    jtxtDniIngresante.setText("");
                    jtxtNombreIngresante.setText("");
                    jtxtCodigoIngresante.setText("");
                    jcomboboxCiclo.setSelectedIndex(-1);
                    jcomboboxEspecialidad.setSelectedIndex(-1);
                    jcomboboxSede.setSelectedIndex(-1);
                    jcomboboxProyecto.setSelectedIndex(-1);
                } else {
                    JOptionPane.showMessageDialog(null, "Error al registrar ingresante");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al insertar, verifique que ciclo, especialidad, sede y proyecto no esten vacios");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al insertar, verifique que nombre y codigo no esten vacio");
        }
    }//GEN-LAST:event_jbtnRegistrarIngresanteActionPerformed

    private void jcomboboxEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboboxEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboboxEspecialidadActionPerformed

    private void jtxtBuscarCicloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarCicloKeyReleased
        String ciclo_nombre = jtxtBuscarCiclo.getText().trim();

        if (!ciclo_nombre.isEmpty()) {
            List<Ciclo> ciclos = cicloLogic.buscarCicloPorNombre(ciclo_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Ciclo ciclo : ciclos) {
                model.addElement(ciclo.getNombre());
            }
            jcomboboxCiclo.setModel(model);
        } else {
            jcomboboxCiclo.setModel(new DefaultComboBoxModel<>());
        }
    }//GEN-LAST:event_jtxtBuscarCicloKeyReleased

    private void jtxtBuscarSedeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarSedeKeyReleased
        String sede_nombre = jtxtBuscarSede.getText().trim();
        if (!sede_nombre.isEmpty()) {
            List<Sede> sedes = sedeLogic.buscarSedePorNombre(sede_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Sede sede : sedes) {
                model.addElement(sede.getNombre());
            }
            jcomboboxSede.setModel(model);
        }
    }//GEN-LAST:event_jtxtBuscarSedeKeyReleased

    private void jtxtBuscarEspecialidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarEspecialidadKeyReleased
        String especialidad_nombre = jtxtBuscarEspecialidad.getText().trim();
        if (!especialidad_nombre.isEmpty()) {
            List<Especialidad> especialidades = especialidadLogic.buscarEspecialidadPorNombre(especialidad_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Especialidad especialidad : especialidades) {
                model.addElement(especialidad.getNombre());
            }
            jcomboboxEspecialidad.setModel(model);
        }
    }//GEN-LAST:event_jtxtBuscarEspecialidadKeyReleased

    private void jtxtBuscarProyectoPorIdKeyReleased(java.awt.event.KeyEvent evt) throws SQLException {//GEN-FIRST:event_jtxtBuscarProyectoPorIdKeyReleased
        String proyecto_id = jtxtBuscarProyectoPorId.getText().trim();
        if (!proyecto_id.isEmpty() && proyecto_id.matches("[1-9]\\d*")) {
            int proyecto_id_int = Integer.parseInt(proyecto_id);
            List<Proyecto> proyectos = proyectoLogic.buscarProyectoPorId(proyecto_id_int);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Proyecto proyecto : proyectos) {
                model.addElement(proyecto.getTitulo());
            }
            jcomboboxProyecto.setModel(model);
        }
    }//GEN-LAST:event_jtxtBuscarProyectoPorIdKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarIngresante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarIngresante dialog = new FrmRegistrarIngresante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PROYECTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbtnRegistrarIngresante;
    private javax.swing.JButton jbtnSalirRegistrarIngresante;
    private javax.swing.JComboBox<String> jcomboboxCiclo;
    private javax.swing.JComboBox<String> jcomboboxEspecialidad;
    private javax.swing.JComboBox<String> jcomboboxProyecto;
    private javax.swing.JComboBox<String> jcomboboxSede;
    private javax.swing.JTextField jtxtBuscarCiclo;
    private javax.swing.JTextField jtxtBuscarEspecialidad;
    private javax.swing.JTextField jtxtBuscarProyectoPorId;
    private javax.swing.JTextField jtxtBuscarSede;
    private javax.swing.JTextField jtxtCodigoIngresante;
    private javax.swing.JTextField jtxtDniIngresante;
    private javax.swing.JTextField jtxtNombreIngresante;
    // End of variables declaration//GEN-END:variables
}
