/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgrado.postgradosistema.cliente.area;

import com.postgrado.postgradosistema.cliente.FrmPrincipal;
import com.postgrado.postgradosistema.cliente.ciclo.FrmCiclo;
import com.postgrado.postgradosistema.cliente.especialidad.FrmEspecialidad;
import com.postgrado.postgradosistema.cliente.ingresante.FrmIngresante;
import com.postgrado.postgradosistema.cliente.proyecto.FrmProyecto;
import com.postgrado.postgradosistema.cliente.sede.FrmSede;
import com.postgrado.postgradosistema.cliente.usuario.FrmUsuario;
import com.postgrado.postgradosistema.logic.AreaLogic;
import com.postgrado.postgradosistema.modelo.Area;
import login.FrmLogin1;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import java.util.List;

/**
 * @author ESTUDIANTE-WALTHER GALAN VITE
 */
public class FrmArea extends javax.swing.JFrame {
    AreaLogic areaLogic = new AreaLogic();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form FrmArea
     */
    public FrmArea() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/enfermeria.png")).getImage());
        //Si se desea que liste una vez que se seleccione el menu, descomentar la siguiente linea
        //listarTablaAreas();
        if (FrmLogin1.tipoUsuario.equals("Administrador")) {
            jMenuMantenimiento.setVisible(true);
            jMenuRegistro.setVisible(true);
        } else {
            jMenuMantenimiento.setVisible(true);
            jMenuRegistro.setVisible(false);
        }
        listarTablaAreas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtBuscarPorNombreArea = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnMostrarTablaArea = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbtnRegistrarArea = new javax.swing.JButton();
        jbtnModificarArea = new javax.swing.JButton();
        jbtnEliminarArea = new javax.swing.JButton();
        jbtnMenu = new javax.swing.JButton();
        jScrollArea = new javax.swing.JScrollPane();
        jTableAreas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuMantenimiento = new javax.swing.JMenu();
        jMenuItemArea = new javax.swing.JMenuItem();
        jMenuItemCiclo = new javax.swing.JMenuItem();
        jMenuItemEspecialidad = new javax.swing.JMenuItem();
        jMenuItemSede = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuRegistro = new javax.swing.JMenu();
        jMenuItemProyecto = new javax.swing.JMenuItem();
        jMenuItemIngresante = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel1.setText("ÁREA");

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel2.setText("BUSCAR");

        jLabel3.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel3.setText("Nombre");

        jtxtBuscarPorNombreArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarPorNombreAreaKeyReleased(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/area.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N

        jbtnMostrarTablaArea.setBackground(new java.awt.Color(204, 204, 204));
        jbtnMostrarTablaArea.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnMostrarTablaArea.setText("Listar");
        jbtnMostrarTablaArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarTablaAreaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBuscarPorNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jbtnMostrarTablaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(82, 82, 82)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtBuscarPorNombreArea, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addComponent(jbtnMostrarTablaArea, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 530, 520));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jbtnRegistrarArea.setBackground(new java.awt.Color(204, 204, 204));
        jbtnRegistrarArea.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnRegistrarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        jbtnRegistrarArea.setText("Registrar");
        jbtnRegistrarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarAreaActionPerformed(evt);
            }
        });

        jbtnModificarArea.setBackground(new java.awt.Color(204, 204, 204));
        jbtnModificarArea.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnModificarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        jbtnModificarArea.setText("Modificar");
        jbtnModificarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarAreaActionPerformed(evt);
            }
        });

        jbtnEliminarArea.setBackground(new java.awt.Color(204, 204, 204));
        jbtnEliminarArea.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnEliminarArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        jbtnEliminarArea.setText("Eliminar");
        jbtnEliminarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarAreaActionPerformed(evt);
            }
        });

        jbtnMenu.setBackground(new java.awt.Color(204, 204, 204));
        jbtnMenu.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.png"))); // NOI18N
        jbtnMenu.setText("Menú Principal");
        jbtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jbtnRegistrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jbtnModificarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jbtnEliminarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jbtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnModificarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEliminarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRegistrarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1060, 90));

        jScrollArea.setBackground(new java.awt.Color(255, 255, 255));

        jTableAreas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "ESTADO"
            }
        ));
        jTableAreas.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollArea.setViewportView(jTableAreas);
        if (jTableAreas.getColumnModel().getColumnCount() > 0) {
            jTableAreas.getColumnModel().getColumn(0).setMinWidth(30);
            jTableAreas.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableAreas.getColumnModel().getColumn(2).setMinWidth(50);
            jTableAreas.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel1.add(jScrollArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 530, 520));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenuMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        jMenuMantenimiento.setText("Mantenimiento");
        jMenuMantenimiento.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N

        jMenuItemArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/area.png"))); // NOI18N
        jMenuItemArea.setText("Área");
        jMenuItemArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAreaActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemArea);

        jMenuItemCiclo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciclo.png"))); // NOI18N
        jMenuItemCiclo.setText("Ciclo");
        jMenuItemCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCicloActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemCiclo);

        jMenuItemEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/especialidad.png"))); // NOI18N
        jMenuItemEspecialidad.setText("Especialidad");
        jMenuItemEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEspecialidadActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemEspecialidad);

        jMenuItemSede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sede.png"))); // NOI18N
        jMenuItemSede.setText("Sede");
        jMenuItemSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSedeActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemSede);

        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuMantenimiento.add(jMenuItemUsuario);

        jMenuBar1.add(jMenuMantenimiento);

        jMenuRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proyectos.png"))); // NOI18N
        jMenuRegistro.setText("Registro");
        jMenuRegistro.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N

        jMenuItemProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono-proyecto.png"))); // NOI18N
        jMenuItemProyecto.setText("Proyecto");
        jMenuItemProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProyectoActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemProyecto);

        jMenuItemIngresante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estudiante.png"))); // NOI18N
        jMenuItemIngresante.setText("Estudiante");
        jMenuItemIngresante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIngresanteActionPerformed(evt);
            }
        });
        jMenuRegistro.add(jMenuItemIngresante);

        jMenuBar1.add(jMenuRegistro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAreaActionPerformed
        this.setVisible(false);
        FrmArea a = new FrmArea();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItemAreaActionPerformed

    private void jMenuItemCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCicloActionPerformed

        this.setVisible(false);
        FrmCiclo c = new FrmCiclo();
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItemCicloActionPerformed

    private void jMenuItemEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEspecialidadActionPerformed
        this.setVisible(false);
        FrmEspecialidad e = new FrmEspecialidad();
        e.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEspecialidadActionPerformed

    private void jMenuItemSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSedeActionPerformed
        this.setVisible(false);
        FrmSede s = new FrmSede();
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSedeActionPerformed

    private void jMenuItemProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProyectoActionPerformed
        this.setVisible(false);
        FrmProyecto e = new FrmProyecto();
        e.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProyectoActionPerformed

    private void jMenuItemIngresanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIngresanteActionPerformed

        this.setVisible(false);
        FrmIngresante i = new FrmIngresante();
        i.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIngresanteActionPerformed

    private void jbtnRegistrarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarAreaActionPerformed

        FrmRegistrarArea regisarea = new FrmRegistrarArea(this, true);
        regisarea.setVisible(true);
    }//GEN-LAST:event_jbtnRegistrarAreaActionPerformed

    private void jbtnModificarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarAreaActionPerformed
        int filaSeleccionada = jTableAreas.getSelectedRow();
        if (filaSeleccionada != -1) {
            //Si la la columna Estado es igual a "Inactivo" no se puede modificar
            if (jTableAreas.getValueAt(filaSeleccionada, 2).toString().equals("I")) {
                JOptionPane.showMessageDialog(null, "No se puede modificar un área inactiva");
            } else {
                int id = Integer.parseInt(jTableAreas.getValueAt(filaSeleccionada, 0).toString());
                String nombre = jTableAreas.getValueAt(filaSeleccionada, 1).toString();

                FrmModificarArea modiarea = new FrmModificarArea(this, true);
                modiarea.setDatos(id, nombre);
                modiarea.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }

    }//GEN-LAST:event_jbtnModificarAreaActionPerformed

    private void jbtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMenuActionPerformed
        this.setVisible(false);
        if (FrmLogin1.tipoUsuario.equals("Administrador")) {
            FrmPrincipal frmPrincipal = new FrmPrincipal();
            frmPrincipal.setVisible(true);
        } else {
            FrmPrincipal frmPrincipal = new FrmPrincipal();
            frmPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_jbtnMenuActionPerformed

    private void jbtnMostrarTablaAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarTablaAreaActionPerformed
        listarTablaAreas();
    }//GEN-LAST:event_jbtnMostrarTablaAreaActionPerformed

    private void jtxtBuscarPorNombreAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarPorNombreAreaKeyReleased
        String nombre = jtxtBuscarPorNombreArea.getText().trim();
        if (!nombre.isEmpty()) {
            List<Area> areas = areaLogic.buscarAreaPorNombre(nombre);
            modelo = (DefaultTableModel) jTableAreas.getModel();
            modelo.setRowCount(0); // Limpiar filas existentes en la tabla

            // lista areas encontradas en la busqueda desde la ultima a la primera
            Object[] ob = new Object[3];
            for (int i = areas.size() - 1; i >= 0; i--) {
                ob[0] = areas.get(i).getId();
                ob[1] = areas.get(i).getNombre();
                ob[2] = areas.get(i).getEs_area();
                modelo.addRow(ob);
            }
        } else {
            listarTablaAreas();
        }
    }//GEN-LAST:event_jtxtBuscarPorNombreAreaKeyReleased

    private void jbtnEliminarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarAreaActionPerformed

        int filaSeleccionada = jTableAreas.getSelectedRow();
        if (filaSeleccionada != -1) {
            if (jTableAreas.getValueAt(filaSeleccionada, 2).toString().equals("I")) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar un área inactiva");
            } else {
                int id = Integer.parseInt(jTableAreas.getValueAt(filaSeleccionada, 0).toString());
                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el área?", "Eliminar área", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    Area area = new Area();
                    area.setId(id);
                    if (areaLogic.inactivarArea(area)) {
                        JOptionPane.showMessageDialog(null, "Se eliminó el área correctamente");

                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo eliminar el área.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se eliminó el área.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una fila para eliminar.");
        }
    }//GEN-LAST:event_jbtnEliminarAreaActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        this.setVisible(false);
        FrmUsuario u = new FrmUsuario();
        u.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmArea().setVisible(true);
            }
        });
    }

    //    private void limpiarTabla() {
//        for (int i = 0; i < modelo.getRowCount(); i++) {
//            modelo.removeRow(i);
//            i = i - 1;
//        }
//    }
    public void listarTablaAreas() {
        List<Area> areas = areaLogic.listaAreas();
        modelo = (DefaultTableModel) jTableAreas.getModel();
        modelo.setRowCount(0); // Limpiar filas existentes en la tabla
        Object[] ob = new Object[3];
        for (int i = areas.size() - 1; i >= 0; i--) {
            ob[0] = areas.get(i).getId();
            ob[1] = areas.get(i).getNombre();
            ob[2] = areas.get(i).getEs_area();
            modelo.addRow(ob);
        }
        jTableAreas.setModel(modelo);
        JTableHeader header = jTableAreas.getTableHeader();
        header.setOpaque(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemArea;
    private javax.swing.JMenuItem jMenuItemCiclo;
    private javax.swing.JMenuItem jMenuItemEspecialidad;
    private javax.swing.JMenuItem jMenuItemIngresante;
    private javax.swing.JMenuItem jMenuItemProyecto;
    private javax.swing.JMenuItem jMenuItemSede;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuMantenimiento;
    private javax.swing.JMenu jMenuRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollArea;
    private javax.swing.JTable jTableAreas;
    private javax.swing.JButton jbtnEliminarArea;
    private javax.swing.JButton jbtnMenu;
    private javax.swing.JButton jbtnModificarArea;
    private javax.swing.JButton jbtnMostrarTablaArea;
    private javax.swing.JButton jbtnRegistrarArea;
    private javax.swing.JTextField jtxtBuscarPorNombreArea;
    // End of variables declaration//GEN-END:variables


}
