/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.postgrado.postgradosistema.cliente.FrmPrincipal;
import com.postgrado.postgradosistema.logic.UsuarioLogic;
import com.postgrado.postgradosistema.modelo.Usuario;

import javax.swing.*;
import java.awt.*;

/**
 * @author windows10
 */
public class FrmLogin1 extends javax.swing.JFrame {
    public static String tipoUsuario;
    UsuarioLogic userLogic = new UsuarioLogic();

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin1() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/enfermeria.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtcontraseña = new javax.swing.JPasswordField();
        jtextusuario = new javax.swing.JTextField();
        btnLogear = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 690));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenfinal.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 204, 255), null));
        jPanel2.setForeground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginfinal.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel3.setText("USUARIO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        jLabel4.setText("CONTRASEÑA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 303, -1, -1));

        jtxtcontraseña.setForeground(new java.awt.Color(0, 0, 0));
        jtxtcontraseña.setBorder(null);
        jtxtcontraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtcontraseñaMousePressed(evt);
            }
        });
        jPanel2.add(jtxtcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 344, 360, 50));

        jtextusuario.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jtextusuario.setForeground(new java.awt.Color(0, 0, 0));
        jtextusuario.setToolTipText("");
        jtextusuario.setBorder(null);
        jtextusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtextusuarioMousePressed(evt);
            }
        });
        jPanel2.add(jtextusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 201, 360, 55));

        btnLogear.setBackground(new java.awt.Color(204, 204, 204));
        btnLogear.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        btnLogear.setText("LOGIN");
        btnLogear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogearActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 127, 49));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 269, 360, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 400, 360, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 509, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtextusuarioMousePressed
        jtextusuario.setForeground(Color.black);
    }//GEN-LAST:event_jtextusuarioMousePressed

    private void jtxtcontraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtcontraseñaMousePressed
        jtxtcontraseña.setForeground(Color.black);
    }//GEN-LAST:event_jtxtcontraseñaMousePressed

    private void btnLogearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogearActionPerformed
        try {
            UsuarioLogic usuarioLogic = new UsuarioLogic();
            String dniTxt = jtextusuario.getText();
            String pass = jtxtcontraseña.getText();
            if (!dniTxt.isEmpty() && !pass.isEmpty()){
                int dni = Integer.parseInt(dniTxt);
                Usuario usuario = usuarioLogic.loginUser(dni, pass);
                if (usuario.getNombre() == null){
                    JOptionPane.showMessageDialog(null, "Las credenciales son incorrectas", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if (usuario.getEs_usuario().equalsIgnoreCase("I")){
                    JOptionPane.showMessageDialog(null, "El usuario se encuentra inactivo", "Advertencia", JOptionPane.WARNING_MESSAGE);
                } else if(usuario.getRol().equals("Administrador")){
                    tipoUsuario = "Administrador";
                    FrmPrincipal frmPrincipal = new FrmPrincipal(usuario);
                    JOptionPane.showMessageDialog(null, "Bienvenido Administrador: " + usuario.getNombre(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    frmPrincipal.setVisible(true);
                    this.dispose();
                } else if (usuario.getRol().equals("Asistente")){
                    tipoUsuario = "Asistente";
                    FrmPrincipal frmPrincipal = new FrmPrincipal(usuario);
                    JOptionPane.showMessageDialog(null, "Bienvenido Asistente: " + usuario.getNombre(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                    frmPrincipal.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Sucedio algo en los permisos del Usuario:  " + usuario.getNombre(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                }
            }else {
                JOptionPane.showMessageDialog(null, "Debe ingresar todos los campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error en el sistema", "Advertencia", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnLogearActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jtextusuario;
    private javax.swing.JPasswordField jtxtcontraseña;
    // End of variables declaration//GEN-END:variables
}
