/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.postgrado.postgradosistema.cliente.proyecto;

import com.postgrado.postgradosistema.logic.EspecialidadLogic;
import com.postgrado.postgradosistema.logic.IngresanteLogic;
import com.postgrado.postgradosistema.logic.ProyectoLogic;
import com.postgrado.postgradosistema.modelo.Especialidad;
import com.postgrado.postgradosistema.modelo.Ingresante;
import com.postgrado.postgradosistema.modelo.Proyecto;
import java.util.ArrayList;

import javax.swing.*;
import java.util.List;

/**
 * @author ESTUDIANTE-WALTHER GALAN VITE
 */
public class FrmRegistrarProyecto extends javax.swing.JDialog {

    EspecialidadLogic especialidadLogic = new EspecialidadLogic();
    IngresanteLogic ingresanteLogic = new IngresanteLogic();
    int xMouse, yMouse;

    /**
     * Creates new form FrmRegistrarProyecto
     */
    public FrmRegistrarProyecto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/enfermeria.png")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtAsesoraProyecto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtBuscarResDesignacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtResEjecucionProyecto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtResCambioJuradoProyecto = new javax.swing.JTextField();
        PROYECTO = new javax.swing.JLabel();
        jtxtBuscarIngresan3 = new javax.swing.JTextField();
        jcomboboxIngresant2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtResCambioTitulo = new javax.swing.JTextField();
        jtxtResSustentacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTituloProyecto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtJuradoProyecto = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtOtrosProyecto = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jtxtBuscarEspecialidad = new javax.swing.JTextField();
        jtxtBuscarIngresante1 = new javax.swing.JTextField();
        jtxtBuscarIngresant2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jcomboboxEspecilidad = new javax.swing.JComboBox<>();
        jcomboboxIngresan3 = new javax.swing.JComboBox<>();
        jcomboboxIngresante1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jbtnRegistrarProyecto = new javax.swing.JButton();
        jbtnSalirRegistrarProyecto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRAR PROYECTO DE TESIS DE SEGUNDA ESPECIALIDAD");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel3.setText("AUTOR - 03");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 109, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel4.setText("ASESOR(A)*");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 109, -1));
        jPanel2.add(jtxtAsesoraProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 410, 30));

        jLabel5.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel5.setText("JURADO *");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 109, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel6.setText("RES. - DESIGNACIÓN *");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));
        jPanel2.add(jtxtBuscarResDesignacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 410, 30));

        jLabel7.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel7.setText("RES. - EJECUCIÓN");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));
        jPanel2.add(jtxtResEjecucionProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 410, 30));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel8.setText("RES. - CAMBIOJURADO");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));
        jPanel2.add(jtxtResCambioJuradoProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 310, 410, 30));

        PROYECTO.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        PROYECTO.setText("RES. - CAMBIOTITULO");
        jPanel2.add(PROYECTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, -1, -1));

        jtxtBuscarIngresan3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarIngresan3KeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarIngresan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 410, 30));

        jPanel2.add(jcomboboxIngresant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 410, 30));

        jLabel9.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel9.setText("ESPECIALIDAD*");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel10.setText("RES. - SUSTENTACIÓN");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel11.setText("OTROS");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, -1, -1));
        jPanel2.add(jtxtResCambioTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 410, 30));
        jPanel2.add(jtxtResSustentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 410, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar02.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jtxtTituloProyecto.setColumns(20);
        jtxtTituloProyecto.setLineWrap(true);
        jtxtTituloProyecto.setRows(5);
        jScrollPane1.setViewportView(jtxtTituloProyecto);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 410, 40));

        jtxtJuradoProyecto.setColumns(20);
        jtxtJuradoProyecto.setLineWrap(true);
        jtxtJuradoProyecto.setRows(5);
        jScrollPane2.setViewportView(jtxtJuradoProyecto);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 410, 40));

        jtxtOtrosProyecto.setColumns(20);
        jtxtOtrosProyecto.setLineWrap(true);
        jtxtOtrosProyecto.setRows(5);
        jScrollPane3.setViewportView(jtxtOtrosProyecto);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, 410, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel12.setText("TITULO *");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 109, -1));

        jtxtBuscarEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBuscarEspecialidadActionPerformed(evt);
            }
        });
        jtxtBuscarEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarEspecialidadKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 410, 30));

        jtxtBuscarIngresante1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarIngresante1KeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarIngresante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 410, 30));

        jtxtBuscarIngresant2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBuscarIngresant2KeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBuscarIngresant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 410, 30));

        jLabel13.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel13.setText("AUTOR - 01*");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 109, -1));

        jLabel14.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel14.setText("AUTOR - 02");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 109, -1));

        jcomboboxEspecilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboboxEspecilidadActionPerformed(evt);
            }
        });
        jPanel2.add(jcomboboxEspecilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 410, 30));

        jPanel2.add(jcomboboxIngresan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 410, 30));

        jPanel2.add(jcomboboxIngresante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 410, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1341, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jbtnRegistrarProyecto.setBackground(new java.awt.Color(204, 204, 204));
        jbtnRegistrarProyecto.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnRegistrarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        jbtnRegistrarProyecto.setText("Registrar");
        jbtnRegistrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarProyectoActionPerformed(evt);
            }
        });

        jbtnSalirRegistrarProyecto.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSalirRegistrarProyecto.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        jbtnSalirRegistrarProyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jbtnSalirRegistrarProyecto.setText("Salir");
        jbtnSalirRegistrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirRegistrarProyectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(jbtnSalirRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(425, 425, 425))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSalirRegistrarProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirRegistrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirRegistrarProyectoActionPerformed

        this.dispose();
    }//GEN-LAST:event_jbtnSalirRegistrarProyectoActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jbtnRegistrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarProyectoActionPerformed
        String titulo = jtxtTituloProyecto.getText().trim();
        String nombreingresante1 = (String) jcomboboxIngresante1.getSelectedItem();
        String nombreingresante2 = (String) jcomboboxIngresant2.getSelectedItem();
        String nombreingresante3 = (String) jcomboboxIngresan3.getSelectedItem();
        String asesora = jtxtAsesoraProyecto.getText().trim();
        String jurado = jtxtJuradoProyecto.getText().trim();
        String res_designacion = jtxtBuscarResDesignacion.getText().trim();
        String res_ejecucion = jtxtResEjecucionProyecto.getText().trim();
        String res_cambioJurado = jtxtResCambioJuradoProyecto.getText().trim();
        String res_sustentacion = jtxtResSustentacion.getText().trim();
        String res_cambioTitulo = jtxtResCambioTitulo.getText().trim();
        String otro = jtxtOtrosProyecto.getText().trim();
        String nombreEspecialidad = (String) jcomboboxEspecilidad.getSelectedItem();

        if (!titulo.isEmpty() && !asesora.isEmpty() && !jurado.isEmpty() && !res_designacion.isEmpty()) {
            EspecialidadLogic especialidadLogic = new EspecialidadLogic();
            IngresanteLogic ingresanteLogic = new IngresanteLogic();
            List<Especialidad> especialidades = especialidadLogic.buscarEspecialidadPorNombre(nombreEspecialidad);
            List<Ingresante> ingresantes1 = ingresanteLogic.buscaringresantePorNombre(nombreingresante1);
            List<Ingresante> ingresantes2 = new ArrayList<>();
            List<Ingresante> ingresantes3 = new ArrayList<>();
            if (nombreingresante2 != null && !nombreingresante2.isEmpty()) {
                ingresantes2 = ingresanteLogic.buscaringresantePorNombre(nombreingresante2);
            }
            if (nombreingresante3 != null && !nombreingresante3.isEmpty()) {
                ingresantes3 = ingresanteLogic.buscaringresantePorNombre(nombreingresante3);
            }
            if (!especialidades.isEmpty()) {
                Especialidad especialidadSeleccionda = especialidades.get(0);
                Ingresante ingresante1Seleccionda = ingresantes1.get(0);
                Ingresante ingresante2Seleccionda = (!ingresantes2.isEmpty()) ? ingresantes2.get(0) : null;
                Ingresante ingresante3Seleccionda = (!ingresantes3.isEmpty()) ? ingresantes3.get(0) : null;

                Proyecto proyecto = new Proyecto();
                proyecto.setTitulo(titulo);
                proyecto.setAsesora(asesora);
                proyecto.setJurado(jurado);
                proyecto.setRes_designacion(res_designacion);
                proyecto.setRes_ejecucion(res_ejecucion);
                proyecto.setRes_cambioJurado(res_cambioJurado);
                proyecto.setRes_sustentacion(res_sustentacion);
                proyecto.setRes_cambioTitulo(res_cambioTitulo);
                proyecto.setOtros(otro);
                proyecto.setEspecialidad(especialidadSeleccionda);
                proyecto.setIngresante1(ingresante1Seleccionda);
                proyecto.setIngresante2(ingresante2Seleccionda);
                proyecto.setIngresante3(ingresante3Seleccionda);

                ProyectoLogic proyectoLogic = new ProyectoLogic();
                proyectoLogic.registrarProyecto(proyecto);
                JOptionPane.showMessageDialog(this, "Se inserto correctamente");
                jtxtTituloProyecto.setText("");
                jtxtAsesoraProyecto.setText("");
                jtxtJuradoProyecto.setText("");
                jtxtBuscarResDesignacion.setText("");
                jtxtResEjecucionProyecto.setText("");
                jtxtResCambioJuradoProyecto.setText("");
                jtxtResCambioTitulo.setText("");
                jtxtResSustentacion.setText("");
                jtxtOtrosProyecto.setText("");
                jcomboboxEspecilidad.setSelectedIndex(-1);
                jcomboboxIngresante1.setSelectedIndex(-1);
                jcomboboxIngresant2.setSelectedIndex(-1);
                jcomboboxIngresan3.setSelectedIndex(-1);

            } else {
                JOptionPane.showMessageDialog(this, "No se pudo insertar, verifique que la Especilidad no este vacio");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo insertar, verifique los campos obligatorios no esten vacio");
        }
    }//GEN-LAST:event_jbtnRegistrarProyectoActionPerformed

    private void jtxtBuscarIngresan3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarIngresan3KeyReleased

        String ingresante3_nombre = jtxtBuscarIngresan3.getText().trim();

        if (!ingresante3_nombre.isEmpty()) {
            List<Ingresante> ingresantes = ingresanteLogic.buscaringresantePorNombre(ingresante3_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Ingresante ingresante : ingresantes) {
                model.addElement(ingresante.getNombre());
            }
            jcomboboxIngresan3.setModel(model);
        } else {
            jcomboboxIngresan3.setModel(new DefaultComboBoxModel<>());
        }


    }//GEN-LAST:event_jtxtBuscarIngresan3KeyReleased


    private void jtxtBuscarEspecialidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarEspecialidadKeyReleased
        // TODO add your handling code here:yu
        String especialidad_nombre = jtxtBuscarEspecialidad.getText().trim();

        if (!especialidad_nombre.isEmpty()) {
            List<Especialidad> especialidades = especialidadLogic.buscarEspecialidadPorNombre(especialidad_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Especialidad especialidad : especialidades) {
                model.addElement(especialidad.getNombre());
            }
            jcomboboxEspecilidad.setModel(model);
        } else {
            jcomboboxEspecilidad.setModel(new DefaultComboBoxModel<>());
    }//GEN-LAST:event_jtxtBuscarEspecialidadKeyReleased
    }
    private void jtxtBuscarIngresante1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarIngresante1KeyReleased
        // TODO add your handling code here:
        String ingresante1_nombre = jtxtBuscarIngresante1.getText().trim();

        if (!ingresante1_nombre.isEmpty()) {
            List<Ingresante> ingresantes = ingresanteLogic.buscaringresantePorNombre(ingresante1_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Ingresante ingresante : ingresantes) {
                model.addElement(ingresante.getNombre());
            }
            jcomboboxIngresante1.setModel(model);
        } else {
            jcomboboxIngresante1.setModel(new DefaultComboBoxModel<>());
        }


    }//GEN-LAST:event_jtxtBuscarIngresante1KeyReleased

    private void jtxtBuscarIngresant2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBuscarIngresant2KeyReleased
        // TODO add your handling code here:

        String ingresante2_nombre = jtxtBuscarIngresant2.getText().trim();

        if (!ingresante2_nombre.isEmpty()) {
            List<Ingresante> ingresantes = ingresanteLogic.buscaringresantePorNombre(ingresante2_nombre);
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            for (Ingresante ingresante : ingresantes) {
                model.addElement(ingresante.getNombre());
            }
            jcomboboxIngresant2.setModel(model);
        } else {
            jcomboboxIngresant2.setModel(new DefaultComboBoxModel<>());
        }


    }//GEN-LAST:event_jtxtBuscarIngresant2KeyReleased

    private void jtxtBuscarEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBuscarEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBuscarEspecialidadActionPerformed

    private void jcomboboxEspecilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboboxEspecilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboboxEspecilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarProyecto dialog = new FrmRegistrarProyecto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PROYECTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnRegistrarProyecto;
    private javax.swing.JButton jbtnSalirRegistrarProyecto;
    private javax.swing.JComboBox<String> jcomboboxEspecilidad;
    private javax.swing.JComboBox<String> jcomboboxIngresan3;
    private javax.swing.JComboBox<String> jcomboboxIngresant2;
    private javax.swing.JComboBox<String> jcomboboxIngresante1;
    private javax.swing.JTextField jtxtAsesoraProyecto;
    private javax.swing.JTextField jtxtBuscarEspecialidad;
    private javax.swing.JTextField jtxtBuscarIngresan3;
    private javax.swing.JTextField jtxtBuscarIngresant2;
    private javax.swing.JTextField jtxtBuscarIngresante1;
    private javax.swing.JTextField jtxtBuscarResDesignacion;
    private javax.swing.JTextArea jtxtJuradoProyecto;
    private javax.swing.JTextArea jtxtOtrosProyecto;
    private javax.swing.JTextField jtxtResCambioJuradoProyecto;
    private javax.swing.JTextField jtxtResCambioTitulo;
    private javax.swing.JTextField jtxtResEjecucionProyecto;
    private javax.swing.JTextField jtxtResSustentacion;
    private javax.swing.JTextArea jtxtTituloProyecto;
    // End of variables declaration//GEN-END:variables
}
